# 👋 Welcome to the Project: Modern Linear Algebra

Hi everyone! Welcome aboard 🚀

In this project, we’ll dive into the beautiful and powerful world of **Modern Linear Algebra** — a toolkit that lies at the heart of everything from solving equations to understanding modern AI models.

---

## 🌟 Why Linear Algebra?

Every system of linear equations — like the one shown below — can be elegantly written in matrix form:

$$
Ax = b
$$

Where:
- $A$ is the **coefficient matrix**,
- $x$ is the **vector of unknowns**, and
- $b$ is the **vector of outputs**.

If $A$ is **non-singular**, we can find a unique solution using:

$$
x = A^{-1}b
$$

And that's just the beginning!

---

## 🎯 What Will You Learn?

- How matrices and vectors work together to model real-world systems
- Numerical methods for solving systems efficiently
- Power and shift-invert methods for eigenvalues
- Applications to graph theory, machine learning, and more!

Let’s get started — and enjoy learning together!


In [2]:
#Gaussian Elimination(with pivoting) 

In [51]:
import numpy as np
A=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]],dtype=float)
b=np.array([[8],[-11],[-3]])
A=np.hstack((A,b))
for i in range(A.shape[0]):
    arr=np.abs(A[i:,i])
    max_val = np.max(arr)
    max_idx = np.argmax(arr)+i
    if(max_val==0):
        break;
    A[[i,max_idx]]=A[[max_idx,i]]
    for j in range(i+1,A.shape[0]):
        A[j]=A[j]-A[j][i]/A[i][i]*A[i]
    print(A)
print(A)      

[[ -3.          -1.           2.         -11.        ]
 [  0.           0.33333333   0.33333333   0.66666667]
 [  0.           1.66666667   0.66666667   4.33333333]]
[[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]
[[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]
[[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]


# Back Substitution

Back substitution is used to solve a linear system whose coefficient matrix is upper triangular.

Consider the system $$U\,x = b$$, where
$$
U = \begin{pmatrix}
u_{11} & u_{12} & \cdots & u_{1n} \\[6pt]
0      & u_{22} & \cdots & u_{2n} \\[6pt]
\vdots & \vdots & \ddots & \vdots \\[6pt]
0      & 0      & \cdots & u_{nn}
\end{pmatrix},\quad
x = \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix},\quad
b = \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix}.
$$

The unknowns \(x_i\) are found **starting from the bottom**:

$$
x_n = \frac{b_n}{u_{nn}},
$$

$$
x_{n-1} = \frac{b_{n-1} - u_{\,n-1,n}\,x_n}{u_{\,n-1,n-1}},
$$

$$
x_{n-2} = \frac{b_{n-2} - u_{\,n-2,n-1}\,x_{n-1} - u_{\,n-2,n}\,x_n}{u_{\,n-2,n-2}},
$$

$$
\vdots
$$

$$
x_1 = \frac{b_1 - \bigl(u_{12}x_2 + u_{13}x_3 + \cdots + u_{1n}x_n\bigr)}{u_{11}}.
$$

> **Note:** This requires$$(u_{ii}\neq 0) \forall i$$


**Assignment** Implement Back substitution and calculate the solution for the Linear System given above.  $$\newline$$                                                        What is the time complexity of both 1. Gaussian Elimination 2. Backward Substitution

# LU Decomposition

## 1. Motivation

LU decomposition rewrites a nonsingular matrix $$(A)$$ as the product of a lower-triangular matrix \(L\) (with ones on the diagonal) and an upper-triangular matrix $$U$$ so that solving
$$
Ax = b
$$
reduces to two simpler triangular systems:

1. **Forward substitution**: solve \(Ly = b\).  
2. **Back substitution**: solve \(Ux = y\).

Once you have factored $$A = LU$$(or with pivoting, $$PA = LU$$, you can solve for many different right-hand sides \(b\) in $$O(n^2)$$ time each, after an initial $$O(n^3)$$ factorization.

**Cost:** $$(\tfrac{2}{3}n^3 + O(n^2)$$ floating-point operations overall.  
**Stability:** Partial pivoting (forming a permutation matrix P) keeps the factors well-scaled and controls rounding errors.

---

## 2. Doolittle’s Algorithm

Initialize
$$
L = I,\quad U = 0.
$$
For $$k = 1,2,\dots,n$$

1. **Compute row \(k\) of \(U\):**  
$$
   U_{k,j}
   = A_{k,j}
     - \sum_{i=1}^{k-1} L_{k,i}\,U_{i,j},
   \quad j = k,\dots,n.
$$

2. **Compute column \(k\) of \(L\):**  
   $$
   L_{i,k}
   = \frac{1}{U_{k,k}}
     \Bigl(
       A_{i,k}
       - \sum_{j=1}^{k-1} L_{i,j}\,U_{j,k}
     \Bigr),
   \quad i = k+1,\dots,n.
   $$

---

## 3. Partial Pivoting

To guard against small pivots and round-off:

1. At step \(k\), find row \(\ell \ge k\) maximizing \(\lvert A_{\ell,k}\rvert\).  
2. Swap rows \(k\) and \(\ell\) in \(A\) (and record the swap in \(P\)).  
3. Apply the same Doolittle updates to the permuted matrix.

---

## 4. In-Place Storage

You can overwrite \(A\) in memory:

- Store the strictly lower part of \(A\) as the multipliers $$(L_{i,j}) \hspace1em \forall (i>j)$$  
- Store the upper part (including the diagonal) as the entries $$(U_{i,j})$$

This is the approach used by LAPACK to save space and improve cache performance.

---

## 5. References

- Golub, G. H. & Van Loan, C. F., _Matrix Computations_, 4th ed., Johns Hopkins University Press.  
- Trefethen, L. N. & Bau, D., _Numerical Linear Algebra_, SIAM, 1997.  
